/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments.index'
import { Route as ShipmentsIdRouteImport } from './routes/shipments.$id'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIdRoute = ShipmentsIdRouteImport.update({
  id: '/shipments/$id',
  path: '/shipments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/scan': typeof ScanRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/scan': typeof ScanRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments': typeof ShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/scan': typeof ScanRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/scan'
    | '/shipments/$id'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/audit' | '/scan' | '/shipments/$id' | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/scan'
    | '/shipments/$id'
    | '/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  ScanRoute: typeof ScanRoute
  ShipmentsIdRoute: typeof ShipmentsIdRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/$id': {
      id: '/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof ShipmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  ScanRoute: ScanRoute,
  ShipmentsIdRoute: ShipmentsIdRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
